import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider as JotaiProvider, DevTools } from "@/lib/jotai";
import { CssBaseline, GeistProvider } from "@/lib/geist-ui";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

enum ThemeType {
  LIGHT = "light",
  DARK = "dark",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <JotaiProvider>
      <GeistProvider themeType={ThemeType.DARK}>
        <CssBaseline />
        <html lang="en">
          <body className={inter.className}>
            <DevTools />
            {children}
          </body>
        </html>
      </GeistProvider>
    </JotaiProvider>
  );
}
